name: CO2Rechner
options:
  bundleIdPrefix: com.example
  generateEmptyDirectories: true
  deploymentTarget:
    iOS: "10.0"
targets:
  CO2Rechner:
    type: application
    platform: iOS
    sources:
      - path: CO2Rechner
        excludes:
          - "Assets/*.sketch"
    settings:
      base:
        SWIFT_VERSION: 5.0